services:
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_DB=oshe_payment
      - POSTGRES_USER=oshe
      - POSTGRES_PASSWORD=oshe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
